# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170315_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.IntegerField(choices=[(0, 'Unmarried'), (1, 'Divorcee'), (2, 'Seperated'), (3, 'Widow/Widower')], null=True),
        ),
    ]
