# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_state', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=333, on_delete=django.db.models.deletion.CASCADE, to='users.Cities'),
        ),
    ]
