# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0005_auto_20170315_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=107, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
        ),
    ]
