# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0005_auto_20170315_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'managed': False, 'ordering': ['city_name']},
        ),
        migrations.AddField(
            model_name='user',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address Line 3'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(db_constraint=False, default=107, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country', to_field='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True),
        ),
    ]
