# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(default=107, max_length=5, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country'),
        ),
    ]
