# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170316_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(db_constraint=False, default='India', on_delete=django.db.models.deletion.CASCADE, to='countries_plus.Country', to_field='name'),
        ),
    ]
