# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170317_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='income',
            field=models.IntegerField(choices=[(0, 'Prefer not to say'), (1, 'Under Rs 50,000'), (2, 'Rs 50,000 - Rs 1,00,000'), (3, 'Rs 1,00,000 - Rs 3,00,000'), (4, 'Rs 3,00,000 - Rs 5,00,000'), (4, 'Rs 5,00,000 - Rs 10,00,000'), (6, 'Above Rs 10,00,000')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.IntegerField(choices=[(0, '')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.IntegerField(choices=[(0, '')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification_summary',
            field=models.TextField(null=True),
        ),
    ]
