# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170317_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beard',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hijab',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
