# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='file',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
