# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20170318_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact number of parent'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Father name'),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Father name'),
        ),
    ]
