# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20170318_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_number',
            new_name='parent_contact_no',
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.IntegerField(choices=[(1, 'Alim / Alima'), (2, 'B. Architect'), (3, 'B.E  (Chemical)'), (4, 'B.E  Bio Medical Instrumentation Engineer'), (5, 'B.E ( Automobile Engineering )'), (6, 'B.E ( Civil Engineer )'), (7, 'B.E ( Computer Engineer )'), (8, 'B.E ( Electrical )'), (9, 'B.E ( Electronics &amp; Communication )'), (10, 'B.E ( I.T )'), (11, 'B.E ( Manufacturing )'), (12, 'B.E ( Software Engineer )'), (13, 'B.E (Electronics)'), (14, 'B.E (Industrial)'), (15, 'B.E (Instrumentation &amp; Control)'), (16, 'B.E (Mechanical)'), (17, 'B.E Metallurgy'), (18, 'B.E Structural Engineer'), (19, 'B.E Textile Engineer'), (20, 'B.E.( Plastic )'), (21, 'B.E.(Production)'), (22, 'B.H.M.S'), (23, 'B.P.Ed'), (24, 'B.Tech'), (25, 'Bachelor in Hotel Management'), (26, 'Bachelor in Interior Designing'), (27, 'Bachelor in Prosthetics and Orthotics'), (28, 'Bachelor of an Airhostess'), (29, 'Bachelor of Arts'), (30, 'Bachelor of Business Administration'), (31, 'Bachelor of Commerce'), (32, 'Bachelor of Computer Applications'), (33, 'Bachelor of Computer Science'), (34, 'Bachelor of Design'), (35, 'Bachelor of Education'), (36, 'Bachelor of Engineering civil'), (37, 'Bachelor of Home Science'), (38, 'Bachelor of Management Science for Finance'), (39, 'Bachelor of Medicine in Electro-Homoeopathy'), (40, 'Bachelor of Nursing'), (41, 'Bachelor of Occupational Therapy'), (42, 'Bachelor of Optometrist'), (43, 'Bachelor of Pharmacy'), (44, 'Bachelor of Physiotherapy'), (45, 'Bachelor of Science'), (46, 'Bachelor of Veterinary Science and Animal Husbandry'), (47, 'Bachelors  in  Hospitality &amp; Tourism  Management'), (48, 'Bachelors of Psychology'), (49, 'BAMS'), (50, 'BDS'), (51, 'BE ( Environmental Engineering)'), (52, 'BSW'), (53, 'BUMS'), (54, 'Chartered Accountant'), (55, 'Company Secretary'), (56, 'DHMS'), (57, 'Dialysis Technician Course'), (58, 'Diploma  in Mechanical  Engineering'), (59, 'Diploma  in Multimedia'), (60, 'Diploma Computer Engineer'), (61, 'Diploma Electronic &amp; comm. Engineering'), (62, 'Diploma in Automobiles Engineer'), (63, 'Diploma in Beauty Parlor'), (64, 'Diploma in Ceramic Engineer'), (65, 'Diploma in Chemical Engineering'), (66, 'Diploma in Civil Engineer'), (67, 'Diploma In Computer Application'), (68, 'Diploma in Electrical  Engineering'), (69, 'Diploma in Fashion Designing'), (70, 'Diploma in Home Science'), (71, 'Diploma in Hotel managment'), (72, 'Diploma in Medical Laboratory Technology'), (73, 'Diploma in Nursing'), (74, 'Diploma in Pharmacy'), (75, 'Diploma in Plastic Engineering'), (76, 'Diploma in Software Engineering'), (77, 'Diploma'), (78, 'Fashion Designing'), (79, 'Fine Arts'), (80, 'General Nursing &amp; Midwifery'), (81, 'H.S.C.'), (82, 'I.T Professional'), (83, 'ITI - Industrial Training Institute'), (84, 'LLB'), (85, 'LLM'), (86, 'M. Lib'), (87, 'M.B.A'), (88, 'M.B.B.S.'), (89, 'M.C.A'), (90, 'M.Com.'), (91, 'M.D ( Anesthesia )'), (92, 'M.D (Physician)'), (93, 'M.D (Pidiatric)'), (94, 'M.E  (Chemical)'), (95, 'M.E ( I.T)'), (96, 'M.E ( Mechanical )'), (97, 'M.E (Electronic &amp; Communication )'), (98, 'M.E Civil ( Geotech )'), (99, 'M.E. ( Structure )'), (100, 'M.E.(Production)'), (101, 'M.Ed ( Masters in Education )'), (102, 'M.Pharmacy'), (103, 'M.Phil'), (104, 'M.S.W ( Master in Social Work )'), (105, 'M.Sc ( I.T )'), (106, 'M.Tech'), (107, 'Master  Degree  in Development  Communication'), (108, 'Master  of   Fine Arts'), (109, 'Master in Computer Science'), (110, 'Master Of Accounting and Financial Management'), (111, 'Master of Arts'), (112, 'Master of Computer Engineering'), (113, 'Master of E-Commerce'), (114, 'Master of MASS Comunication'), (115, 'Master of PhysioTherapy'), (116, 'Master of Science'), (117, 'Masters in Clinical Psychology'), (118, 'Masters in Project Management &amp; Security System'), (119, 'MD( Pidiatric)'), (120, 'MDS ( Master of Dental surgery )'), (121, 'NDDY ( Naturopathy Doctor )'), (122, 'Occupational Theraphy'), (123, 'P.G  in Human Resaurce Management'), (124, 'P.T.C'), (125, 'PGDIT'), (126, 'Ph.D'), (127, 'S.S.C.'), (128, 'Sanitary inspector'), (129, 'School level')], null=True),
        ),
    ]
