# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20170319_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_line3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='beard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hijab',
        ),
        migrations.RemoveField(
            model_name='user',
            name='income',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation_summary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_contact_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualification_summary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reason_registration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sect',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
