# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20170319_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family_summary',
        ),
    ]
