# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0002_auto_20170321_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
