# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0003_auto_20170321_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_type',
            field=models.IntegerField(choices=[(1, 'Athletic'), (2, 'Average'), (3, 'Slim'), (4, 'Heavy')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='complexion',
            field=models.IntegerField(choices=[(1, 'Dark'), (2, 'Fair'), (3, 'Very Fair'), (4, 'Wheatish Brown')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.CharField(blank=True, max_length=255, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=255, verbose_name='Height'),
        ),
    ]
