# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0004_auto_20170322_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='complexion',
            field=models.IntegerField(choices=[(1, 'Dark'), (2, 'Fair'), (3, 'Wheatish Brown')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.CharField(blank=True, max_length=255, verbose_name='Weight'),
        ),
    ]
