# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0005_auto_20170322_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mother_tonge',
            field=models.IntegerField(choices=[(1, 'Hindi'), (2, 'Bengali'), (3, 'Telugu'), (4, 'Marathi'), (5, 'Tamil'), (6, 'Urdu'), (7, 'Gujarati'), (8, 'Kannada'), (9, 'Malayalam'), (10, 'Odia'), (11, 'Punjabi'), (12, 'Assamese'), (13, 'Maithili'), (14, 'Bhili/Bhilodi'), (15, 'Santali'), (16, 'Kashmiri'), (17, 'Nepali'), (99, 'Other')], null=True),
        ),
    ]
