# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0006_profile_mother_tonge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mother_tonge',
            new_name='mother_tongue',
        ),
    ]
