# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0007_auto_20170323_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sect',
        ),
        migrations.AddField(
            model_name='profile',
            name='cast',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cast'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sub_cast',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub cast'),
        ),
    ]
