# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='date_submitted',
            field=models.DateField(null=True, verbose_name='Submitted on'),
        ),
    ]
