# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarship_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='ahd_resident',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='scholarship'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='education_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='grant_before',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='statement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='surname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Surname'),
        ),
    ]
