# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_auto_20170328_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='location',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='address',
            field=models.TextField(blank=True, max_length=255, verbose_name='Address'),
        ),
    ]
