# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_auto_20170328_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='ahd_resident',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='grant_before',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
