# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20170328_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='scholarship/documents')),
            ],
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarship.Scholarship'),
        ),
    ]
