# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_auto_20170329_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='contact_number',
            field=models.IntegerField(blank=True, default=None, verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='scholarship/2017'),
        ),
    ]
