# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_auto_20170331_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Number'),
        ),
    ]
